yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.failure_500'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост')

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ("-pub_date",)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments')

    text = models.TextField('Текст комментария',
                            help_text='Введите текст комментария')
    created = models.DateTimeField('Дата публикации',
                                   auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="following")

    class Meta:
        constraints = [models.UniqueConstraint
                       (fields=['user', 'author'], name='unique_follow')]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {'text': "Текст нового поста",
                      'group': "Группа, к которой будет относиться пост"}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {'text': "Текст комментария"}

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow
from .utils import paginate

NUM_MAX: int = 10


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    page_obj = paginate(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.all()
    page_obj = paginate(request, posts_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    fullname = User.objects.get(username=username)
    post_list = Post.objects.filter(author=fullname)
    page_obj = paginate(request, post_list)
    follow = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=fullname).exists()
    context = {
        'page_obj': page_obj,
        'fullname': fullname,
        'follow': follow
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comments = post.comments.all
    context = {
        'page_obj': post,
        'comments': comments,
        'form': CommentForm()
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST or None,
                        files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
    else:
        form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    if post_id and request.user != post.author:
        return redirect("posts:post_detail", post_id=post_id)
    form = PostForm(request.POST or None,
                    instance=post,
                    files=request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id=post_id)
    else:
        form = PostForm(instance=post)
        context = {'form': form, 'is_edit': True, 'post': post, }
        return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = Post.objects.get(id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate(request, post_list)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if request.user != author and not is_follower.exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if not is_edit %}
    Добавить запись  
  {% else %} 
    Редактировать запись
  {% endif %}
{% endblock %} 
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if not is_edit %}
              Добавить запись  
            {% else %} 
              Редактировать запись
            {% endif %}
          </div>
            <div class="card-body">        
              <form method="post" enctype="multipart/form-data" action="{% if not is_edit %}
                                           {% url 'posts:post_create'%}
                                          {% else %}
                                           {% url 'posts:post_edit' post_id=post.id %} 
                                         {% endif %}">                 
                {% csrf_token %}

                {% for field in form %}
                  <div class="form-group">
                    {% if field.errors %}
                      <div class="alert.alert.danger">
                        {{ field.errors }}
                      </div>
                    {% endif %}

                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                  </div>
                {% endfor %}

                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if not is_edit %}
                      Добавить  
                    {% else %} 
                     Сохранить
                   {% endif %}
                  </button>
                </div>
              </form>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
  <head> 
    {% load static %}    
    {% block title %}
    <a><title>Публикации избранных авторов</title></a>
    {% endblock %}
  </head>
  <body>
    <header>      
    </header>
    <main> 
      {% block content %}
      <div class="container py-5">
        <h5>{% include 'posts/includes/switcher.html' %}</h5>     
        <h1>Публикации избранных авторов</h1>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}<br>
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
      </div>
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}  
    </main>         
    <footer class="border-top text-center py-3">   
    </footer>
  </body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}<a><title>{{ group.title }}</a></title>{% endblock title%}
{% block content %}
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        <article>
          <ul>
            <li>
            {% for group in page_obj %}
              Автор: {{ group.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ group.pub_date|date:"d E Y" }}
            </li>
          </ul>  
          {% thumbnail group.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}    
          <p>
            {{ group.text }}
          </p>  
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}       
        </article>
        {% include 'posts/includes/paginator.html' %}
      </div> 
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
  <head> 
    {% load static %}    
    {% block title %}
    <a><title>Последние обновления на сайте</title></a>
    {% endblock %}
  </head>
  <body>
    <header>      
    </header>
    <main> 
      {% block content %}
      <div class="container py-5">
        <h5>{% include 'posts/includes/switcher.html' %}</h5>     
        <h1>Последние обновления на сайте</h1>
        <article>
          
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}<br>
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
      </div>
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}  
    </main>         
    <footer class="border-top text-center py-3">   
    </footer>
  </body>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
<!DOCTYPE html>
<html lang="ru"> 
  <head>  
    {% block title %}
    <a><title> {{ page_obj.text|truncatechars:30 }}</title></a>
    {% endblock %}
  </head>
  <body>
    {% block content %}       
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ page_obj.pub_date|date:"d E Y"}} 
            </li>
            {% if page_obj.group %}   
              <li class="list-group-item">
                Группа: {{ page_obj.group }}
                <a href="{% url 'posts:group_list' page_obj.group.slug %}"><br>
                  все записи группы
                </a>
              {% endif %}
              </li>
              <li class="list-group-item">
                Автор: {{ page_obj.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ page_obj.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' page_obj.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {% thumbnail page_obj.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <br>
            <br>
           {{ page_obj.text }}
           <br>
           <br>
           <a type="button" class="btn btn-outline-primary" 
           href="{% url 'posts:post_edit' post_id=page_obj.id %}">
        Редактировать
        </a>
          </p>
          {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post_id=page_obj.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}
        </article>
      </div> 
    </main>
    {% endblock %}
  </body>
</html>

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru"> 
  <head>  
    {% block title %}
    <a><title>Профайл пользователя {{ fullname.username }} </title></a>
    {% endblock %}
  </head>
  <body>
    {% block content %}       
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ fullname.username }} </h1>
        <h3>Всего постов: {{ fullname.posts.count }} </h3>
        <h6>{% if follow %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' fullname.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' fullname.username %}" role="button"
            >
              Подписаться
            </a>
         {% endif %}
      </div></h6>   
        <article>
            {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ fullname.get_full_name }}  
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a><br>
        </article>       
        {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
            {% if not forloop.last %}<hr>{% endif %}        
        <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}  
      </div>
    </main>
    {% endblock %}
  </body>
</html>